site_name: ohhfishal.io
site_url: https://ohhfishal.github.io
site_description: Official blogging
edit_uri: edit/main/docs/

nav:
  - Home: "index.md"
  - About: "about.md"
  - Projects: "projects.md"
  - Blog: "blog/index.md"

plugins:
  - search
  - git-revision-date
  - rss:
      categories:
        - tags
theme:
  name: terminal
  palette: dark
  features:
    - revision.date
    - revision.history
    - footer.prev_next
    # - navigation.side.indexes
    # - navigation.side.indexes.hide
    - navigation.side.toc
    - navigation.side.toc.hide
    - navigation.side.hide
    # - navigation.top.hide
